### PR TITLE
ci: use local version for testing

### PR DESCRIPTION
**Pull request by Borda**
this enables proper testing of a change from PR 🦩
atm any PR is not really testing code that is changed but the code from the master...

cc: @garciasdos @ArnaudRinquin @piraka9011

### CODE REVIEW

**Comment by Borda** [comment]
@garciasdos @ArnaudRinquin @piraka9011, any chance you could approve CI run? :chipmunk:

**Comment by piraka9011** [comment]
@Borda I'm a contributor, not a member of the org :)
See instead https://github.com/orgs/sliteteam/people

**Comment by Borda** [comment]
> See instead [github.com/orgs/sliteteam/people](https://github.com/orgs/sliteteam/people)

ok, thank you, just seems that others are busy...

**Comment by Calyhre** [comment]
Hello 👋 Sorry I got a bit too conservative with notifications. Thanks for the contribution @Borda!

**Pull request merged**
