### PR TITLE
Add support for running git-crypt in a path other than GITHUB_WORKSPACE

### PR DESCRIPTION
**Pull request by adevine**
Setting a RUN_DIR env var allows executing this from a directory other than GITHUB_WORKSPACE. This may be necessary if you have a build that pulls down multiple repos.

### CODE REVIEW

**Review by ArnaudRinquin — APPROVED** [review]

**Comment by ArnaudRinquin** [comment]
@adevine Thanks for your contribution but I think this might be unecessary: what about using the `working-directory:` instruction in workflows? It's a shame it's not well explained in GitHub Actions docs.

```yaml
- name: Install dependencies
        working-directory: docs
        run: |
          npm install
```

**Comment by jtomaszewski** [comment]
`working-directory` does not work, just tried it:

image

BTW. Shouldn't we be using something like this?

```yaml
with:
  path: docs
```

just like for example you'd pass `path` to `actions/checkout@v2` .

**Comment by edbighead** [comment]
If this can be merged, it might solve the issue when the action runs on custom runners and the `/home/gha-actions-runner/_work/myrepo/myrepo/.git/git-crypt/keys/default` is being owned by `root:root`resulting in
`'/home/gha-actions-runner/_work/myrepo/myrepo/.git/git-crypt/keys/default': Permission denied` during checkout and cleanup steps. 
@ArnaudRinquin you think it can be merged?

**Comment by folgarr** [comment]
@ArnaudRinquin can this be merged? this would also help us quite a bit - thanks!

**Comment by vglafirov** [comment]
There is no activity on this repo for 2 years. I am giving up :(

**Comment by eleni-salamani** [comment]
+1

**Review by ArnaudRinquin — APPROVED** [review]

**Comment by ArnaudRinquin** [comment]
Sorry folks, didn't noticed PR. Let's merge cc @eleni-salamani @vglafirov @folgarr @adevine

**Pull request merged**
